### PR TITLE
Translated to German (DE)

### PR DESCRIPTION
**Pull request by J-Cake**
Added German translations. 

Note that I wasn't able to find any official German Git terminology, so I used what sounded best in my opinion.

### CODE REVIEW

**Comment by crutchcorn** [comment]
@J-Cake thank you so so so much for the contribution! I'm absolutely swamped right now with personal stuff, but I'll be sure to get this looked at and merged within the next few days.

BTW, if you can - can you reach out to me via DMs (I'm @crutchcorn on Twitter or crutchcorn on gmail.com via email), I'd love to send you a care package of sorts for helping us out!

**Comment by J-Cake** [comment]
@crutchcorn That's very kind of you, but you don't need to.

**Comment by J-Cake** [comment]
Hi @crutchcorn I just wanted to mention that I had made another two commits to the fork on my account that weren't merged here. The commits included a) importing the translation file and enabling its use and b) a number of corrections and additions throughout the codebase, relating to translations, such as the `New Repository` button on the start screen. I'm wondering if that was shown in the Pull Request, or whether I'd have to create a new PR.

**Comment by crutchcorn** [comment]
@J-Cake let's go ahead and make a new PR. Make sure to rebase on top of the current `main` branch, as I already made the code changes to enable to German translations

**Comment by J-Cake** [comment]
No problemo

**Pull request merged**
